name: build and release

on:
  push:
    tags:
      - "v**"

env:
  CRATE_NAME: mcp-wos-gibtsn-heid
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  test:
    name: ${{ matrix.platform.os-name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            bin: mcp-wos-gibstn-heid
            name: mcp-wos-gibstn-heid-Linux-x86_64-musl.tar.gz
          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl
            bin: mcp-wos-gibstn-heid
            name: mcp-wos-gibstn-heid-Linux-aarch64-musl.tar.gz
          - os-name: Linux-arm
            runs-on: ubuntu-24.04
            target: arm-unknown-linux-musleabi
            bin: mcp-wos-gibstn-heid
            name: mcp-wos-gibstn-heid-Linux-arm-musl.tar.gz
          - os-name: Linux-i686
            runs-on: ubuntu-24.04
            target: i686-unknown-linux-musl
            bin: mcp-wos-gibstn-heid
            name: mcp-wos-gibstn-heid-Linux-i686-musl.tar.gz
            skip-tests: true
          - os-name: Windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
            bin: mcp-wos-gibstn-heid.exe
            name: mcp-wos-gibstn-heid-Windows-aarch64.zip
            skip-tests: true
          - os-name: Windows-i686
            runs-on: windows-latest
            target: i686-pc-windows-msvc
            bin: mcp-wos-gibstn-heid.exe
            name: mcp-wos-gibstn-heid-Windows-i686.zip
            skip-tests: true
          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            bin: mcp-wos-gibstn-heid.exe
            name: mcp-wos-gibstn-heid-Windows-x86_64.zip
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            bin: mcp-wos-gibstn-heid
            name: mcp-wos-gibstn-heid-Darwin-x86_64.tar.gz
          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            bin: mcp-wos-gibstn-heid
            name: mcp-wos-gibstn-heid-Darwin-aarch64.tar.gz
        toolchain:
          - stable
        include:
          - platform:
              os-name: Linux-x86_64
              runs-on: ubuntu-24.04
              target: x86_64-unknown-linux-musl
              bin: mcp-wos-gibstn-heid
            toolchain: beta
          - platform:
              os-name: Linux-x86_64
              runs-on: ubuntu-24.04
              target: x86_64-unknown-linux-musl
              bin: mcp-wos-gibstn-heid
            toolchain: nightly
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "test"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          # This works around the issue in https://github.com/cross-rs/cross/issues/1450. The `main`
          # branch updated its images long ago, but the last cross release, 0.2.5, is still using
          # Ubuntu 16.04 as the base for some images.
          #
          # This also contains a fix for https://github.com/cross-rs/cross/issues/1619. Previously,
          # we used an earlier commit, but this started erroring because some dependencies included
          # cross config.
          cross-version: 107433fa9d71d7eb506cd5bf5467bab89edb7a52
        if: ${{ !matrix.platform.skip-tests }}
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true
          cross-version: 107433fa9d71d7eb506cd5bf5467bab89edb7a52
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: mcp-wos-gibstn-heid
          target: ${{ matrix.platform.target }}
        if: matrix.toolchain == 'stable'
